"""Adicionando novos campos à tabela produtores

Revision ID: 034485c4d12f
Revises: 
Create Date: 2024-11-25 21:39:18.709102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034485c4d12f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_fazenda', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('area_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('area_agricultavel', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('area_vegetacao', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('culturas', sa.String(length=200), nullable=False))
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtores', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('cpf_cnpj',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
        batch_op.drop_column('culturas')
        batch_op.drop_column('area_vegetacao')
        batch_op.drop_column('area_agricultavel')
        batch_op.drop_column('area_total')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('nome_fazenda')

    # ### end Alembic commands ###
